package pl.edu.wit.todolist.enums;


public enum NotificationType {
    TASK_DUE_SOON,
    TASK_DUE_SOON_5,
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    GROUP_INVITE_RECEIVED,
    GROUP_INVITE_ACCEPTED,
    GROUP_INVITE_REJECTED,
    TASK_ASSIGNED_TO_YOU,
    GROUP_MEMBER_LEFT,
    GROUP_MEMBER_KICKED,
    GROUP_DELETED
}
